# Change these first
owner: noveni # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Ecrannoir
    url: https://www.ecrannoir.be
  - name: Broken Site
    url: https://thissitedoesnotexist.com
  - name: Documentation
    url: https://documentation.ecrannoir.be
  - name: Jehanne Moll
    url: https://jehannemoll.com
  - name: Beauté Engagée
    url: https://www.beaute-engagee.be
  - name: Paloma
    url: https://www.paloma-latelier.be
  - name: Nuance Infuse
    url: https://www.nuanceinfuse.be
  - name: Coma ULG
    url: https://www.coma.uliege.be
  - name: Smart2Circle
    url: https://smart2circle.com
  - name: Chanelle Delbrouck
    url: https://beta.chanelledbck.be
  - name: Portal Herstal
    url: https://portal.fnherstal.com
  - name: Communication Herstal Group
    url: https://communication.herstalgroup.com
  - name: FN Enovation
    url: https://fnenovation.eu
  - name: ESFAM
    url: https://www.esfam.eu

status-website:
  baseUrl: /upptime
  name: Ecran Noir - Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
